### ISSUE TITLE
Sudden OOM error on Longhorn. CuPy leak?

### ISSUE THREAD

**Issue by dialecticDolt** [ut-padas/pyrknn#16]
Not documented too well yet. Mostly making this as a note to myself to investigate and fix this. 

When running 136M SIFT on 16 GPUs for a convergence study of different # of local iterations, I'm observing an OOM error after:
`71 * 5`, `35 * 10`, and `23 * 15` iterations, where the product here is `distributed iterations * local iterations`. 

This is consistent with a memory leak in the local Python a2a CuPy code that hits max GPU memory at ~350 total function calls. 
The memory error usually hits at `gpu.merge_neighbors()` between distributed iterations but I suspect the leak is before this step. 
`gpu.merge_neighbors()` is only called once per distributed iteration.

**Comment by dialecticDolt** [comment]
It fails to happen after `150*15` iterations, when commenting out `py_dfiknn` so that the search phase is a no-op. The memory leak appears to be internal to the HALEN knn kernel and not the tree construction. Still looking into it.

**Comment by dialecticDolt** [comment]
Its not in the C++ code. All allocated memory is freed or is shard memory on the stack. 
Has to be in `dense.pyx `. 

Possibly the `X = X[gids, :]` line, could be similar to the memory problem Jimmy was seeing. 
But I would expect any of the memory operations here to crash MUCH sooner than 350 iterations if they weren't being garbage collected.

Going to try reproducing it on a single GPU with <400 local iterations and no distributed iterations.

**Comment by dialecticDolt** [comment]
hmm, on a single node, it can be reproduced with `23*15` iterations. It doesn't happen for `1x400` iterations.

Its kind of weird that it seems to depend on the number of local iterations but cannot be reproduced without taking distributed iterations. Possibly cudaMalloc interfering with the CuPy mempool. Possible fix is adding an explicit garbage collection step but this will slow down the iteration.

**Comment by dialecticDolt** [comment]
Adding a check on the mempool and clearing it fixed this issue. Closing.

**Comment by dialecticDolt** [comment]
Sadly reopening this. When rerunning some experiments to higher precision a similar issue is now appearing as a segmentation fault.

In progress: Rechecking the mempool clearing above and making sure none of the addresses rely on stale memory. 

```
[c002-005:108095] *** Process received signal ***
[c002-005:108095] Signal: Segmentation fault (11)
[c002-005:108095] Signal code: Address not mapped (1)
[c002-005:108095] Failing at address: 0x1d
[c002-005:108095] [ 0] [0x2000000504d8]
[c002-005:108095] [ 1] [0x0]
[c002-005:108095] [ 2] /home/06081/wlruys/miniconda3/envs/ali/bin/../lib/libcublas.so.10(+0x8d9cfc)[0x200032c69cfc]
[c002-005:108095] [ 3] /home/06081/wlruys/miniconda3/envs/ali/bin/../lib/libcublas.so.10(cublasSgemm_v2+0x836c)[0x2000328a8dec]
[c002-005:108095] [ 4] /home/06081/wlruys/miniconda3/envs/ali/bin/../lib/libcublas.so.10(+0x5a50d4)[0x2000329350d4]
[c002-005:108095] [ 5] /home/06081/wlruys/miniconda3/envs/ali/bin/../lib/libcublas.so.10(cublasSgemmStridedBatched+0x100)[0x2000329266f0]
[c002-005:108095] [ 6] /home/06081/wlruys/miniconda3/envs/ali/lib/python3.9/site-packages/filknn/dense/dense.cpython-39-powerpc64le-linux-gnu.so(_Z11dfi_leafknnPfPiiiiS_S0_ii+0x11fc)[0x20005d51d8e0]
[c002-005:108095] [ 7] /home/06081/wlruys/miniconda3/envs/ali/lib/python3.9/site-packages/filknn/dense/dense.cpython-39-powerpc64le-linux-gnu.so(+0x930c)[0x20005d51930c]
[c002-005:108095] [ 8] /home/06081/wlruys/miniconda3/envs/ali/lib/python3.9/site-packages/filknn/dense/dense.cpython-39-powerpc64le-linux-gnu.so(+0xb9f4)[0x20005d51b9f4]
```

**Comment by dialecticDolt** [comment]
I confirmed that this bug is _not_ the same as the thread starter. However it is similar behavior-wise. For N=8M, d=128, k=32, filknn will crash between the 402rd and 403rd call. This happens with fixed input, with and without MPI, in all configurations of distributed iterations and single-node trees. 

Based on behavior it seems like a memory leak (on C++ side) leading to a silent failed memory allocation. The CuPy memorypool is not holding more data than expected.

**Comment by dialecticDolt** [comment]
Fixed.  The culprit was missing cleanup of cuBLAS handles causing a leak of 8.4 MB per iteration.
